# Generated by Django 4.1.7 on 2023-04-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201019_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Topics',
            new_name='Patients',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='topic',
            new_name='access_key',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='topic_id',
            new_name='patient_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='topic_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='patient_id',
            field=models.ForeignKey(db_column='patient_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patients'),
        ),
        migrations.AddField(
            model_name='messages',
            name='type_id',
            field=models.ForeignKey(db_column='type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.types'),
        ),
    ]
