# Generated by Django 4.1.7 on 2023-04-02 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_types_rename_topics_patients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='type_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
    ]
